services:
  - type: web
    name: project-mani-api
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: HF_TOKEN
        sync: false
      - key: PORT
        value: 3001